// Generated by tools/build.mjs — do not edit.
window.TL = {
 "total": 96.031,
 "scenes": {
  "open": {
   "start": 0,
   "end": 10.385
  },
  "ingredients": {
   "start": 10.385,
   "end": 27.692
  },
  "s1": {
   "start": 27.692,
   "end": 38.077
  },
  "s2": {
   "start": 38.077,
   "end": 45
  },
  "s3": {
   "start": 45,
   "end": 55.385
  },
  "s4": {
   "start": 55.385,
   "end": 62.308
  },
  "s5": {
   "start": 62.308,
   "end": 69.231
  },
  "s6": {
   "start": 69.231,
   "end": 77.308
  },
  "s7": {
   "start": 77.308,
   "end": 88.846
  },
  "close": {
   "start": 88.846,
   "end": 96.031
  }
 },
 "lines": {
  "l01": {
   "start": 1.1,
   "end": 4.35
  },
  "l02": {
   "start": 4.8,
   "end": 7.97
  },
  "l03": {
   "start": 10.935,
   "end": 12.6
  },
  "l04": {
   "start": 13,
   "end": 25.53
  },
  "l05": {
   "start": 28.292,
   "end": 36.192
  },
  "l06": {
   "start": 38.677,
   "end": 43.087
  },
  "l07": {
   "start": 45.6,
   "end": 52.535
  },
  "l08": {
   "start": 55.985,
   "end": 59.8
  },
  "l09": {
   "start": 62.908,
   "end": 65.523
  },
  "l10": {
   "start": 69.831,
   "end": 74.851
  },
  "l11": {
   "start": 77.908,
   "end": 85.803
  },
  "l12": {
   "start": 89.546,
   "end": 91.626
  },
  "l13": {
   "start": 92.126,
   "end": 93.231
  }
 },
 "b": {
  "openEyebrow": 0.5,
  "openPlate": 0.75,
  "openHoney": 3.012,
  "openGarlic": 3.394,
  "openChicken": 3.84,
  "openSweet": 4.8,
  "openSticky": 5.253,
  "openPot": 6.029,
  "ingWindow": 10.785,
  "ingRows": [
   13,
   13.525,
   14.125,
   14.951,
   15.626,
   16.526,
   18.252,
   19.152,
   20.353,
   22.529,
   23.804
  ],
  "s1Drops": [
   29.621,
   30.138,
   30.728,
   31.541,
   32.205,
   33.091
  ],
  "s1Whisk": 33.682,
  "s1Aside": 35.332,
  "s2Saute": 40.777,
  "s2Oil": 41.757,
  "s3Thighs": 45.75,
  "s3Season": 48.237,
  "s3Brown": 49.748,
  "s3Chip": 50.72,
  "s3Flip": 52.785,
  "s4Pour": 56.709,
  "s4Lid": 58.437,
  "s4Lock": 59.95,
  "s5Poultry": 63.577,
  "s5Twenty": 64.611,
  "s5Count": 65.873,
  "s5Done": 67.873,
  "s6Off": 70.483,
  "s6Steam": 71.591,
  "s6Clock": 73.612,
  "s6Ready": 75.251,
  "s7Plate": 78.67,
  "s7Sauce": 79.986,
  "s7Seeds": 83.171,
  "s7Onions": 84.903,
  "s7Stamp": 86.153,
  "closePanel": 89.296,
  "closeTitle": 89.546,
  "closeSlam": 92.176,
  "closeCredit": 93.831,
  "s1Pill": 28.042,
  "s1Head": 28.342,
  "s1Card": 28.742,
  "s2Pill": 38.427,
  "s2Head": 38.727,
  "s2Card": 39.127,
  "s3Pill": 45.35,
  "s3Head": 45.65,
  "s3Card": 46.05,
  "s4Pill": 55.735,
  "s4Head": 56.035,
  "s4Card": 56.435,
  "s5Pill": 62.658,
  "s5Head": 62.958,
  "s5Card": 63.358,
  "s6Pill": 69.581,
  "s6Head": 69.881,
  "s6Card": 70.281,
  "s7Pill": 77.658,
  "s7Head": 77.958,
  "s7Card": 78.358
 }
};
