// Generated by tools/build.mjs — do not edit.
window.TL = {
 "total": 60.813,
 "scenes": {
  "open": {
   "start": 0,
   "end": 7.5
  },
  "ingredients": {
   "start": 7.5,
   "end": 13.846
  },
  "s1": {
   "start": 13.846,
   "end": 21.923
  },
  "s2": {
   "start": 21.923,
   "end": 25.962
  },
  "s3": {
   "start": 25.962,
   "end": 33.462
  },
  "s4": {
   "start": 33.462,
   "end": 37.5
  },
  "s5": {
   "start": 37.5,
   "end": 42.692
  },
  "s6": {
   "start": 42.692,
   "end": 49.038
  },
  "s7": {
   "start": 49.038,
   "end": 56.538
  },
  "close": {
   "start": 56.538,
   "end": 60.813
  }
 },
 "lines": {
  "l01": {
   "start": 0.7,
   "end": 6.675
  },
  "l02": {
   "start": 7.8,
   "end": 12.09
  },
  "l03": {
   "start": 14.146,
   "end": 20.911
  },
  "l04": {
   "start": 22.223,
   "end": 24.918
  },
  "l05": {
   "start": 26.262,
   "end": 32.692
  },
  "l06": {
   "start": 33.762,
   "end": 36.382
  },
  "l07": {
   "start": 37.8,
   "end": 40.58
  },
  "l08": {
   "start": 42.992,
   "end": 47.682
  },
  "l09": {
   "start": 49.338,
   "end": 54.848
  },
  "l10": {
   "start": 57.838,
   "end": 58.813
  }
 },
 "b": {
  "hostIn": 0.35,
  "hostOut": 56.638,
  "openEyebrow": 0.4,
  "openPlate": 0.6,
  "openHoney": 1.447,
  "openGarlic": 1.82,
  "openChicken": 2.256,
  "openSweet": 2.816,
  "openSticky": 3.252,
  "openPot": 3.999,
  "ingWindow": 7.8,
  "ingRows": [
   8.05,
   8.32,
   8.59,
   8.86,
   9.13,
   9.4,
   9.67,
   9.94,
   10.21,
   10.48,
   10.75
  ],
  "s1Drops": [
   14.816,
   15.285,
   15.821,
   16.155,
   16.758,
   17.361
  ],
  "s1Whisk": 17.964,
  "s1Aside": 19.27,
  "s2Saute": 22.223,
  "s2Oil": 23.147,
  "s2Hot": 24.071,
  "s3Thighs": 26.162,
  "s3Season": 26.812,
  "s3Brown": 27.87,
  "s3Chip": 28.845,
  "s3Flip": 30.26,
  "s4Pour": 33.662,
  "s4Lid": 34.943,
  "s4Lock": 35.727,
  "s5Poultry": 37.8,
  "s5Twenty": 38.85,
  "s5Count": 39.839,
  "s5Done": 42.18,
  "s6Off": 43.042,
  "s6Steam": 42.992,
  "s6Clock": 44.787,
  "s6Denied": 45.748,
  "s6Ready": 47.882,
  "s7Plate": 49.338,
  "s7Sauce": 50.035,
  "s7Seeds": 50.733,
  "s7Onions": 51.919,
  "s7Ranch": 53.383,
  "s7Denied": 54.011,
  "s7Stamp": 55.198,
  "closePanel": 56.888,
  "closeTitle": 57.088,
  "closeSlam": 57.888,
  "closeCredit": 59.313,
  "quips": [
   [
    "open",
    5.43,
    "You take the credit."
   ],
   [
    "s1",
    19.17,
    "Yes, this one gets a bowl."
   ],
   [
    "s2",
    24.071,
    "Stand back."
   ],
   [
    "s3",
    30.51,
    "Don't poke them. We said what we said."
   ],
   [
    "s4",
    35.727,
    "No peeking."
   ],
   [
    "s5",
    39.839,
    "Go sit down."
   ],
   [
    "s6",
    45.598,
    "Opening it early is not on the menu."
   ],
   [
    "s7",
    53.383,
    "Ranch is not invited."
   ]
  ],
  "s1Pill": 14.096,
  "s1Head": 14.196,
  "s1Card": 14.446,
  "s2Pill": 22.173,
  "s2Head": 22.273,
  "s2Card": 22.523,
  "s3Pill": 26.212,
  "s3Head": 26.312,
  "s3Card": 26.562,
  "s4Pill": 33.712,
  "s4Head": 33.812,
  "s4Card": 34.062,
  "s5Pill": 37.75,
  "s5Head": 37.85,
  "s5Card": 38.1,
  "s6Pill": 42.942,
  "s6Head": 43.042,
  "s6Card": 43.292,
  "s7Pill": 49.288,
  "s7Head": 49.388,
  "s7Card": 49.638
 }
};
